export const categoriesSeed = [
  {
    slug: "stationery",
    name: "Stationery / Office Supplies",
    description: "Office supplies, paper, pens, folders, binders, desk accessories",
    icon: "📎",
    defaultVendors: ["amazon", "staples", "officedepot"],
    detectionKeywords: [
      "paper", "pen", "pencil", "folder", "binder", "clip", "stapler",
      "tape", "envelope", "notebook", "marker", "highlighter", "eraser",
      "ruler", "scissors", "glue", "label", "stamp", "ink", "toner",
      "cartridge", "stationery", "office", "desk", "file", "laminate",
      "sticky note", "post-it", "whiteboard", "calculator", "diary",
      "calendar", "planner", "punch", "shredder", "copier",
    ],
  },
  {
    slug: "deck_engine",
    name: "Deck / Engine Stores",
    description: "Marine deck supplies, engine parts, tools, safety equipment",
    icon: "⚓",
    defaultVendors: ["amazon-deck", "mcmaster", "grainger"],
    detectionKeywords: [
      "deck", "engine", "marine", "IMO", "SOLAS", "mooring",
      "rope", "wire", "shackle", "paint", "anti-fouling",
      "valve", "gasket", "bearing", "pump", "filter",
      "safety", "fire", "lifeboat", "navigation",
      "wrench", "socket", "drill", "grinder", "welding",
      "bolt", "nut", "screw", "washer", "fitting",
      "hose", "clamp", "coupling", "flange", "pipe",
      "lubricant", "grease", "oil", "coolant", "sealant",
    ],
  },
  {
    slug: "galley_kitchen",
    name: "Galley / Kitchen Stores",
    description: "Kitchen equipment, food service supplies, galley provisions",
    icon: "🍳",
    defaultVendors: ["amazon-galley", "webstaurant", "equippers"],
    detectionKeywords: [
      "kitchen", "galley", "cook", "food", "pan", "pot", "oven",
      "microwave", "refrigerator", "freezer", "dishwasher", "blender",
      "mixer", "cutting board", "knife", "utensil", "plate", "bowl",
      "glass", "cup", "tray", "serving", "container", "storage",
      "foil", "wrap", "napkin", "towel", "detergent", "sanitizer",
      "apron", "gloves", "thermometer", "scale", "ladle", "spatula",
    ],
  },
];
