export const vendorsSeed = [
  // ===================== STATIONERY =====================
  {
    name: "Amazon",
    slug: "amazon",
    category: "stationery",
    enabled: true,
    baseUrl: "https://www.amazon.com",
    searchUrlPattern: "https://www.amazon.com/s?k={{query}}",
    authRequired: false,
    authType: "none" as const,
    loginUrl: "https://www.amazon.com/ap/signin",
    dashboardUrl: "https://www.amazon.com/gp/css/homepage.html",
    sessionMaxAgeHours: 336, // 14 days
    preferredStrategy: "http" as const,
    needsJsRendering: false,
    rateLimitMs: 2000,
    cacheFreshnessHours: 24,
    extractionHints:
      "Amazon uses ASINs as product IDs. Look for Prime pricing. Prices shown per unit or per pack. Check 'Subscribe & Save' vs one-time price.",
    searchQueryTemplate:
      "Use consumer-friendly terms. Include brand names if known. Add 'pack' or 'box' for bulk items.",
    healthStatus: "healthy" as const,
  },
  {
    name: "Staples",
    slug: "staples",
    category: "stationery",
    enabled: true,
    baseUrl: "https://www.staples.com",
    searchUrlPattern: "https://www.staples.com/search?query={{query}}",
    authRequired: false,
    authType: "none" as const,
    loginUrl: "https://www.staples.com/account/login",
    dashboardUrl: "https://www.staples.com/account",
    sessionMaxAgeHours: 168, // 7 days
    preferredStrategy: "http" as const,
    needsJsRendering: false,
    rateLimitMs: 2000,
    cacheFreshnessHours: 24,
    extractionHints:
      "Staples uses SKU numbers. Prices may show business pricing tiers. Look for 'Add to Cart' price as the real price.",
    searchQueryTemplate:
      "Use office supply terms. Staples prefers specific product names over generic descriptions.",
    healthStatus: "healthy" as const,
  },
  {
    name: "OfficeBasics",
    slug: "officebasics",
    category: "stationery",
    enabled: true,
    baseUrl: "https://www.officebasics.com",
    searchUrlPattern: "https://www.officebasics.com/search?q={{query}}",
    authRequired: true,
    authType: "playwright" as const,
    loginUrl: "https://www.officebasics.com/login",
    dashboardUrl: "https://www.officebasics.com/account",
    sessionMaxAgeHours: 48,
    preferredStrategy: "playwright" as const,
    needsJsRendering: true,
    rateLimitMs: 3000,
    cacheFreshnessHours: 48,
    extractionHints:
      "OfficeBasics is a B2B supplier. Prices are login-gated. Look for wholesale/bulk pricing. Product codes are internal SKUs.",
    searchQueryTemplate:
      "Use standard office supply terminology. OfficeBasics catalog is smaller — use broader terms if specific ones fail.",
    healthStatus: "healthy" as const,
  },
  {
    name: "Office Depot",
    slug: "officedepot",
    category: "stationery",
    enabled: true,
    baseUrl: "https://www.officedepot.com",
    searchUrlPattern: "https://www.officedepot.com/catalog/search.do?Ntt={{query}}",
    authRequired: false,
    authType: "none" as const,
    loginUrl: "https://www.officedepot.com/account/login",
    dashboardUrl: "https://www.officedepot.com/account",
    sessionMaxAgeHours: 168,
    preferredStrategy: "http" as const,
    needsJsRendering: false,
    rateLimitMs: 2000,
    cacheFreshnessHours: 24,
    extractionHints:
      "Office Depot uses item numbers. Check for in-store vs online availability. Prices may differ for business accounts.",
    searchQueryTemplate:
      "Similar to Staples — use standard office supply terms. Include quantity descriptors (box, pack, ream).",
    healthStatus: "healthy" as const,
  },

  // ===================== DECK / ENGINE =====================
  {
    name: "Amazon",
    slug: "amazon-deck",
    category: "deck_engine",
    enabled: true,
    baseUrl: "https://www.amazon.com",
    searchUrlPattern: "https://www.amazon.com/s?k={{query}}",
    authRequired: false,
    authType: "none" as const,
    sessionMaxAgeHours: 336,
    preferredStrategy: "http" as const,
    needsJsRendering: false,
    rateLimitMs: 2000,
    cacheFreshnessHours: 24,
    extractionHints:
      "For industrial/marine items on Amazon, look for industrial & scientific category results. Prices per unit. Check seller ratings.",
    searchQueryTemplate:
      "Use technical/industrial terms. Include material specifications. Add 'marine grade' for deck items.",
    healthStatus: "healthy" as const,
  },
  {
    name: "McMaster-Carr",
    slug: "mcmaster",
    category: "deck_engine",
    enabled: true,
    baseUrl: "https://www.mcmaster.com",
    searchUrlPattern: "https://www.mcmaster.com/{{query}}",
    authRequired: true,
    authType: "playwright" as const,
    loginUrl: "https://www.mcmaster.com/login",
    dashboardUrl: "https://www.mcmaster.com/orders",
    sessionMaxAgeHours: 48,
    preferredStrategy: "playwright" as const,
    needsJsRendering: true,
    rateLimitMs: 3000,
    cacheFreshnessHours: 48,
    extractionHints:
      "McMaster uses part numbers not ASINs. Prices shown per unit. Look for 'Each' pricing. Aggressive anti-bot — use stealth mode.",
    searchQueryTemplate:
      "Use technical/industrial terms. Include dimensions in inches. Use McMaster-style terminology (e.g., 'socket head cap screw' not 'bolt').",
    healthStatus: "healthy" as const,
  },
  {
    name: "Grainger",
    slug: "grainger",
    category: "deck_engine",
    enabled: true,
    baseUrl: "https://www.grainger.com",
    searchUrlPattern: "https://www.grainger.com/search?searchQuery={{query}}",
    authRequired: false,
    authType: "none" as const,
    loginUrl: "https://www.grainger.com/login",
    dashboardUrl: "https://www.grainger.com/myaccount",
    sessionMaxAgeHours: 168,
    preferredStrategy: "http" as const,
    needsJsRendering: false,
    rateLimitMs: 2000,
    cacheFreshnessHours: 24,
    extractionHints:
      "Grainger uses item numbers. Large industrial catalog. List price shown publicly, account pricing may differ. Check for minimum order quantities.",
    searchQueryTemplate:
      "Use industrial/MRO terminology. Grainger has a huge catalog — be specific with dimensions and materials.",
    healthStatus: "healthy" as const,
  },

  // ===================== GALLEY / KITCHEN =====================
  {
    name: "Amazon",
    slug: "amazon-galley",
    category: "galley_kitchen",
    enabled: true,
    baseUrl: "https://www.amazon.com",
    searchUrlPattern: "https://www.amazon.com/s?k={{query}}",
    authRequired: false,
    authType: "none" as const,
    sessionMaxAgeHours: 336,
    preferredStrategy: "http" as const,
    needsJsRendering: false,
    rateLimitMs: 2000,
    cacheFreshnessHours: 24,
    extractionHints:
      "For kitchen/galley items on Amazon, look for restaurant supply and commercial kitchen results. Check for NSF certification mentions.",
    searchQueryTemplate:
      "Use commercial kitchen/restaurant supply terms. Add 'commercial' or 'restaurant grade' for professional items.",
    healthStatus: "healthy" as const,
  },
  {
    name: "WebstaurantStore",
    slug: "webstaurant",
    category: "galley_kitchen",
    enabled: true,
    baseUrl: "https://www.webstaurantstore.com",
    searchUrlPattern:
      "https://www.webstaurantstore.com/search/{{query}}.html",
    authRequired: false,
    authType: "none" as const,
    sessionMaxAgeHours: 168,
    preferredStrategy: "http" as const,
    needsJsRendering: false,
    rateLimitMs: 2000,
    cacheFreshnessHours: 72,
    extractionHints:
      "WebstaurantStore has public prices. Large restaurant supply catalog. Look for bulk pricing tiers. Free shipping over certain amounts.",
    searchQueryTemplate:
      "Use restaurant/foodservice industry terms. WebstaurantStore has extensive filters — be specific about size, material, and capacity.",
    healthStatus: "healthy" as const,
  },
  {
    name: "Equippers",
    slug: "equippers",
    category: "galley_kitchen",
    enabled: true,
    baseUrl: "https://www.quippers.com",
    searchUrlPattern: "https://www.quippers.com/search?q={{query}}",
    authRequired: false,
    authType: "none" as const,
    sessionMaxAgeHours: 168,
    preferredStrategy: "http" as const,
    needsJsRendering: false,
    rateLimitMs: 2000,
    cacheFreshnessHours: 72,
    extractionHints:
      "Equippers is a restaurant equipment supplier. Public pricing. Smaller catalog than WebstaurantStore.",
    searchQueryTemplate:
      "Use commercial kitchen equipment terms. Include brand names if known.",
    healthStatus: "healthy" as const,
  },
];
